name: FastAPI Deployment to S3

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install FastAPI, Mangum, etc.

      # Step to zip the FastAPI app and other files
      - name: Zip FastAPI app
        run: |
          mkdir -p deploy
          zip -r deploy/fastapi_app.zip SourceCode/  # Zip the entire folder

      # Configure AWS credentials using AWS GitHub Action from Marketplace
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Hardcoded for now
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Hardcoded for now
          aws-region: "us-east-1"

      # Step to upload the zip file to S3
      - name: Upload to S3
        run: |
          aws s3 cp deploy/fastapi_app.zip s3://mydata-venkey/fastapi_app.zip
