name: FastAPI Deployment to S3 - Minimal Test

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This action should be valid

      # Minimal AWS credentials setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Testing this action
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Test with secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # Simple step to verify the setup
      - name: Verify AWS CLI
        run: aws s3 ls  # Just list the buckets as a test
